type Query {
    user(id: ID!): UserProfile
    me: UserProfile
}

type Mutation {
    login(email: String!, password: String!): String
    register(email: String!, password: String!, name: String!): String
    createUser(email: String!, password: String!, name: String!): UserProfile
    updateUser(id: ID!, name: String!, email: String!, password: String!): UserProfile
    deleteUser(id: ID!): Boolean
}

type UserProfile {
    id: ID
    name: String
    email: String
    role: RoleInfo
    createdAt: String
}

type RoleInfo {
    id: ID
    name: String
}

type Trip {
    id: ID
    destination: String
    bookings: [Booking]
}

type Booking {
    id: ID
    status: String
}
