spring.application.name=user-service

server.port=8030
spring.profiles.active=prod

spring.datasource.password=admin
spring.datasource.username=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none